# Generated by Django 5.2.7 on 2025-12-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Durum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], default='Aktif', max_length=20, verbose_name='Durum')),
            ],
        ),
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150, verbose_name='İlan Başlığı')),
                ('durum', models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], default='Aktif', max_length=20, verbose_name='İlan Durumu')),
            ],
        ),
    ]
