# Generated by Django 5.2.7 on 2025-12-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilan',
            options={'verbose_name': 'İlan', 'verbose_name_plural': 'İlanlar'},
        ),
        migrations.AddField(
            model_name='durum',
            name='pasif_nedeni',
            field=models.CharField(choices=[('Satildi', 'Satıldı'), ('Kiralandi', 'Kiralandı'), ('Yayin_Suresi_Bitti', 'Yayın Süresi Bitti'), ('Yayindan_Kaldirildi', 'Yayından Kaldırıldı'), ('Diger', 'Diğer')], default='Diğer', max_length=20, verbose_name='Pasif Nedeni'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='pasif_nedeni',
            field=models.CharField(choices=[('Satildi', 'Satıldı'), ('Kiralandi', 'Kiralandı'), ('Yayin_Suresi_Bitti', 'Yayın Süresi Bitti'), ('Yayindan_Kaldirildi', 'Yayından Kaldırıldı'), ('Diger', 'Diğer')], default='Diğer', max_length=20, verbose_name='Pasif Nedeni'),
        ),
    ]
