# Generated by Django 5.2.7 on 2025-12-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0002_alter_ilan_options_durum_pasif_nedeni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durum',
            name='pasif_nedeni',
            field=models.CharField(choices=[('Satildi', 'Satıldı'), ('Kiralandi', 'Kiralandı'), ('Yayin_Suresi_Bitti', 'Yayın Süresi Bitti'), ('Yayindan_Kaldirildi', 'Yayından Kaldırıldı'), ('Diger', 'Diğer')], default='Diger', max_length=20, verbose_name='Pasif Nedeni'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='pasif_nedeni',
            field=models.CharField(choices=[('Satildi', 'Satıldı'), ('Kiralandi', 'Kiralandı'), ('Yayin_Suresi_Bitti', 'Yayın Süresi Bitti'), ('Yayindan_Kaldirildi', 'Yayından Kaldırıldı'), ('Diger', 'Diğer')], default='Diger', max_length=20, verbose_name='Pasif Nedeni'),
        ),
    ]
